In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno
!pip install squarify
import squarify as sq

import plotly.express as px
import plotly.graph_objs as go
import plotly.offline as pyoff

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting squarify
  Downloading squarify-0.4.3-py3-none-any.whl (4.3 kB)
Installing collected packages: squarify
Successfully installed squarify-0.4.3

In [2]:
plt.style.use('seaborn')
sns.set(rc={'figure.figsize':(15, 8)})

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Produksi Perikanan

In [4]:
prod = pd.read_excel('drive/MyDrive/Capstone Tetris/Produksi.xlsx')

In [5]:
prod.head()

  Jenis Usaha Provinsi Jenis Ikan  Tahun  Volume Produksi  Nilai Produksi
0    BUDIDAYA     ACEH    BANDENG   2011         16746.80       251202000
1    BUDIDAYA     ACEH    BANDENG   2012         18492.30       295876800
2    BUDIDAYA     ACEH    BANDENG   2013         20530.00       315768921
3    BUDIDAYA     ACEH    BANDENG   2014         23914.10       373190273
4    BUDIDAYA     ACEH    BANDENG   2015         24930.75       393447645

# Luas Lahan Budidaya

In [6]:
df_luas_raw =pd.read_excel('drive/MyDrive/Capstone Tetris/Luas Lahan.xlsx')

In [7]:
df_luas_raw.head()

,Provinsi,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0
0,ACEH,550748880.0,552473814.0,555653500.0,556477848.0,521092673.0,602956400.0,602956400.0,691389303.0,1.036911e+09,1.447134e+09
1,BALI,26669000.0,22636000.0,27598000.0,20831000.0,19843000.0,24267000.0,24267000.0,8150145.0,1.410324e+07,2.257368e+07
2,BANTEN,111622060.0,162822096.0,167244030.0,159605860.0,160115900.0,158864016.0,158864016.0,158557360.0,2.482529e+08,2.043835e+08
3,BENGKULU,96755672.0,77108300.0,87062200.0,89538100.0,115162199.0,104011400.0,104011400.0,170239534.0,3.129969e+08,3.575244e+07
4,DAERAH ISTIMEWA YOGYAKARTA,10415813.0,9735177.0,11383432.0,58543300.0,13583400.0,14671200.0,14671200.0,13635085.0,1.688868e+07,1.681590e+07

In [8]:
df_luas_raw.shape

(34, 11)

In [9]:
luas = df_luas_raw.transpose().iloc[1].to_numpy()
i = 2
while i < df_luas_raw.shape[1]:
    data= df_luas_raw.transpose().iloc[i].to_numpy()
    luas = np.concatenate((luas, data))
    i = i + 1
print(luas)
print(len(luas))

[550748880.0 26669000.0 111622060.0 96755672.0 10415813.0 6391800.0
 57230971.0 32328699.0 1293307500.0 482545100.0 1060007510.0 241655889.0
 155240868.0 60253800.0 1613047079.0 0.0 5784800.0 53778380.0 546976610.0
 467591700.0 17560300.0 279817064.0 79120000.0 19520700.0 4091000.0
 63669640.0 218297350.0 1605669015.0 301711494.0 486150000.0 117305532.0
 130930507.0 614431153.0 205442000.0 552473814.0 22636000.0 162822096.0
 77108300.0 9735177.0 5329522.0 54833570.0 29861313.0 1291694991.0
 517823100.0 1057150775.0 250297080.0 158262206.0 67272800.0 1780961583.0
 0.0 5144500.0 69188581.0 383340230.0 504296460.0 27877100.0 310793935.0
 85140000.0 24375004.0 17535284.0 31114030.0 226788064.0 1591648236.0
 303648718.0 482945400.0 143684332.0 153683854.0 646684465.0 209619800.0
 555653500.0 27598000.0 167244030.0 87062200.0 11383432.0 4118684.0
 58897111.0 28221500.0 1301096077.0 400064099.0 2301956738.0 269885246.0
 184441777.0 66324745.0 1733877670.0 0.0 3409900.0 85902502.0 527554968.0
 524456600.0 19276443.0 269810078.0 113219000.0 23673273.0 18238630.0
 32729930.0 224518285.0 1746525076.0 346520004.0 493514600.0 159520700.0
 158396022.0 643685042.0 195591900.0 556477848.0 20831000.0 159605860.0
 89538100.0 58543300.0 4035814.0 84384018.0 21933044.0 1293085373.0
 550488789.0 2240441431.0 260061620.0 188582409.0 75564340.0 1711193213.0
 0.0 2795200.0 90722339.0 531743700.0 76198489.0 18335128.0 285922264.0
 125260154.0 32565803.0 17800846.0 34770668.0 243542000.0 1743007000.0
 350995600.0 488916109.0 161894039.0 161299110.0 651271633.0 205675900.0
 521092673.0 19843000.0 160115900.0 115162199.0 13583400.0 6786500.0
 84578303.0 27374300.0 1134655700.0 566521800.0 2248385067.0 177057900.0
 188761878.0 82350569.0 1233680886.0 811560270.0 2019450.0 93267170.0
 558242700.0 176207100.0 40515200.0 246712800.0 127711400.0 31795803.0
 441429500.0 36053700.0 260375000.0 1779641000.0 421964600.0 383704000.0
 163113121.0 173957689.0 665266400.0 224953079.0 602956400.0 24267000.0
 158864016.0 104011400.0 14671200.0 5447718.0 86817900.0 28090500.0
 1294772400.0 609754067.0 2248394067.0 163908820.0 258246522.0 84832000.0
 230555854.0 760280000.0 4188999.0 55105500.0 489097900.0 113048200.0
 67333000.0 301677600.0 125060060.0 31684803.0 26556200.0 46327700.0
 266850000.0 1778505000.0 361624100.0 441659240.0 163113121.0 173917689.0
 651229089.0 239569083.0 602956400.0 24267000.0 158864016.0 104011400.0
 14671200.0 5447718.0 86817900.0 28090500.0 1294772400.0 609754067.0
 2248394067.0 163908820.0 258246522.0 84832000.0 230555854.0 760280000.0
 4188999.0 55105500.0 489097900.0 113048200.0 67333000.0 301677600.0
 125060060.0 31684803.0 26556200.0 46327700.0 266850000.0 1778505000.0
 361624100.0 441659240.0 163113121.0 173917689.0 651229089.0 239569083.0
 691389303.0 8150145.0 158557360.0 170239534.0 13635085.0 1672365.0
 64394107.0 21407311.0 99049038.0 1466633624.0 2424093286.0 169526776.0
 120164716.0 4271651.0 840578880.0 1340165675.0 3246431.0 3757828.0
 505532168.0 64622997.0 219274.0 291772823.0 136860356.0 2741976.0
 2433801.0 30826550.0 279539000.0 1667674751.0 615739769.0 408022507.0
 90431510.0 88708424.0 401179189.0 560511513.0 1036910719.0 14103237.0
 248252857.0 312996886.0 16888678.0 219345.0 85844379.0 21275124.0
 2613324448.0 893045550.0 928615924.0 73611090.0 959513063.0 108818189.0
 1033721835.0 1564323132.0 5152407.0 8050923.0 353602046.0 92455074.0
 4517525.0 416231706.0 94024967.0 8786882.0 1774245.0 25773564.0
 257784234.0 2084914231.0 395084084.0 663171892.0 61983713.0 119953044.0
 316353014.0 444364692.0 1447133550.0 22573679.0 204383542.0 35752441.0
 16815899.0 143036.0 84724331.0 18986474.0 817960074.0 469245224.0
 778553930.0 84238210.0 158721684.0 82481435.0 1032948187.0 1387244215.0
 4903275.0 5528645.0 388192603.0 48846268.0 3960993.0 275104913.0
 95751349.0 4886777.0 1218403.0 25595129.0 205325144.0 1664188455.0
 309154503.0 265938132.0 40955375.0 123614096.0 307726190.0 279435415.0]
340

In [10]:
from itertools import repeat
year = []
i = 2011
while i < 2021:
    year.extend(repeat(i,df_luas_raw.shape[0]))
    i = i + 1
print(year)
print(len(year))

[2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020]
340

In [11]:
provinsi = df_luas_raw.transpose().iloc[0].to_numpy()
i = 2
while i < df_luas_raw.shape[1]:
    data = df_luas_raw.transpose().iloc[0].to_numpy()
    provinsi = np.concatenate((provinsi, data))
    i = i + 1
print(provinsi)
print(len(provinsi))

['ACEH' 'BALI' 'BANTEN' 'BENGKULU' 'DAERAH ISTIMEWA YOGYAKARTA'
 'DKI JAKARTA' 'GORONTALO' 'JAMBI' 'JAWA BARAT' 'JAWA TENGAH' 'JAWA TIMUR'
 'KALIMANTAN BARAT' 'KALIMANTAN SELATAN' 'KALIMANTAN TENGAH'
 'KALIMANTAN TIMUR' 'KALIMANTAN UTARA' 'KEPULAUAN BANGKA BELITUNG'
 'KEPULAUAN RIAU' 'LAMPUNG' 'MALUKU' 'MALUKU UTARA' 'NUSA TENGGARA BARAT'
 'NUSA TENGGARA TIMUR' 'PAPUA' 'PAPUA BARAT' 'RIAU' 'SULAWESI BARAT'
 'SULAWESI SELATAN' 'SULAWESI TENGAH' 'SULAWESI TENGGARA' 'SULAWESI UTARA'
 'SUMATERA BARAT' 'SUMATERA SELATAN' 'SUMATERA UTARA' 'ACEH' 'BALI'
 'BANTEN' 'BENGKULU' 'DAERAH ISTIMEWA YOGYAKARTA' 'DKI JAKARTA'
 'GORONTALO' 'JAMBI' 'JAWA BARAT' 'JAWA TENGAH' 'JAWA TIMUR'
 'KALIMANTAN BARAT' 'KALIMANTAN SELATAN' 'KALIMANTAN TENGAH'
 'KALIMANTAN TIMUR' 'KALIMANTAN UTARA' 'KEPULAUAN BANGKA BELITUNG'
 'KEPULAUAN RIAU' 'LAMPUNG' 'MALUKU' 'MALUKU UTARA' 'NUSA TENGGARA BARAT'
 'NUSA TENGGARA TIMUR' 'PAPUA' 'PAPUA BARAT' 'RIAU' 'SULAWESI BARAT'
 'SULAWESI SELATAN' 'SULAWESI TENGAH' 'SULAWESI TENGGARA' 'SULAWESI UTARA'
 'SUMATERA BARAT' 'SUMATERA SELATAN' 'SUMATERA UTARA' 'ACEH' 'BALI'
 'BANTEN' 'BENGKULU' 'DAERAH ISTIMEWA YOGYAKARTA' 'DKI JAKARTA'
 'GORONTALO' 'JAMBI' 'JAWA BARAT' 'JAWA TENGAH' 'JAWA TIMUR'
 'KALIMANTAN BARAT' 'KALIMANTAN SELATAN' 'KALIMANTAN TENGAH'
 'KALIMANTAN TIMUR' 'KALIMANTAN UTARA' 'KEPULAUAN BANGKA BELITUNG'
 'KEPULAUAN RIAU' 'LAMPUNG' 'MALUKU' 'MALUKU UTARA' 'NUSA TENGGARA BARAT'
 'NUSA TENGGARA TIMUR' 'PAPUA' 'PAPUA BARAT' 'RIAU' 'SULAWESI BARAT'
 'SULAWESI SELATAN' 'SULAWESI TENGAH' 'SULAWESI TENGGARA' 'SULAWESI UTARA'
 'SUMATERA BARAT' 'SUMATERA SELATAN' 'SUMATERA UTARA' 'ACEH' 'BALI'
 'BANTEN' 'BENGKULU' 'DAERAH ISTIMEWA YOGYAKARTA' 'DKI JAKARTA'
 'GORONTALO' 'JAMBI' 'JAWA BARAT' 'JAWA TENGAH' 'JAWA TIMUR'
 'KALIMANTAN BARAT' 'KALIMANTAN SELATAN' 'KALIMANTAN TENGAH'
 'KALIMANTAN TIMUR' 'KALIMANTAN UTARA' 'KEPULAUAN BANGKA BELITUNG'
 'KEPULAUAN RIAU' 'LAMPUNG' 'MALUKU' 'MALUKU UTARA' 'NUSA TENGGARA BARAT'
 'NUSA TENGGARA TIMUR' 'PAPUA' 'PAPUA BARAT' 'RIAU' 'SULAWESI BARAT'
 'SULAWESI SELATAN' 'SULAWESI TENGAH' 'SULAWESI TENGGARA' 'SULAWESI UTARA'
 'SUMATERA BARAT' 'SUMATERA SELATAN' 'SUMATERA UTARA' 'ACEH' 'BALI'
 'BANTEN' 'BENGKULU' 'DAERAH ISTIMEWA YOGYAKARTA' 'DKI JAKARTA'
 'GORONTALO' 'JAMBI' 'JAWA BARAT' 'JAWA TENGAH' 'JAWA TIMUR'
 'KALIMANTAN BARAT' 'KALIMANTAN SELATAN' 'KALIMANTAN TENGAH'
 'KALIMANTAN TIMUR' 'KALIMANTAN UTARA' 'KEPULAUAN BANGKA BELITUNG'
 'KEPULAUAN RIAU' 'LAMPUNG' 'MALUKU' 'MALUKU UTARA' 'NUSA TENGGARA BARAT'
 'NUSA TENGGARA TIMUR' 'PAPUA' 'PAPUA BARAT' 'RIAU' 'SULAWESI BARAT'
 'SULAWESI SELATAN' 'SULAWESI TENGAH' 'SULAWESI TENGGARA' 'SULAWESI UTARA'
 'SUMATERA BARAT' 'SUMATERA SELATAN' 'SUMATERA UTARA' 'ACEH' 'BALI'
 'BANTEN' 'BENGKULU' 'DAERAH ISTIMEWA YOGYAKARTA' 'DKI JAKARTA'
 'GORONTALO' 'JAMBI' 'JAWA BARAT' 'JAWA TENGAH' 'JAWA TIMUR'
 'KALIMANTAN BARAT' 'KALIMANTAN SELATAN' 'KALIMANTAN TENGAH'
 'KALIMANTAN TIMUR' 'KALIMANTAN UTARA' 'KEPULAUAN BANGKA BELITUNG'
 'KEPULAUAN RIAU' 'LAMPUNG' 'MALUKU' 'MALUKU UTARA' 'NUSA TENGGARA BARAT'
 'NUSA TENGGARA TIMUR' 'PAPUA' 'PAPUA BARAT' 'RIAU' 'SULAWESI BARAT'
 'SULAWESI SELATAN' 'SULAWESI TENGAH' 'SULAWESI TENGGARA' 'SULAWESI UTARA'
 'SUMATERA BARAT' 'SUMATERA SELATAN' 'SUMATERA UTARA' 'ACEH' 'BALI'
 'BANTEN' 'BENGKULU' 'DAERAH ISTIMEWA YOGYAKARTA' 'DKI JAKARTA'
 'GORONTALO' 'JAMBI' 'JAWA BARAT' 'JAWA TENGAH' 'JAWA TIMUR'
 'KALIMANTAN BARAT' 'KALIMANTAN SELATAN' 'KALIMANTAN TENGAH'
 'KALIMANTAN TIMUR' 'KALIMANTAN UTARA' 'KEPULAUAN BANGKA BELITUNG'
 'KEPULAUAN RIAU' 'LAMPUNG' 'MALUKU' 'MALUKU UTARA' 'NUSA TENGGARA BARAT'
 'NUSA TENGGARA TIMUR' 'PAPUA' 'PAPUA BARAT' 'RIAU' 'SULAWESI BARAT'
 'SULAWESI SELATAN' 'SULAWESI TENGAH' 'SULAWESI TENGGARA' 'SULAWESI UTARA'
 'SUMATERA BARAT' 'SUMATERA SELATAN' 'SUMATERA UTARA' 'ACEH' 'BALI'
 'BANTEN' 'BENGKULU' 'DAERAH ISTIMEWA YOGYAKARTA' 'DKI JAKARTA'
 'GORONTALO' 'JAMBI' 'JAWA BARAT' 'JAWA TENGAH' 'JAWA TIMUR'
 'KALIMANTAN BARAT' 'KALIMANTAN SELATAN' 'KALIMANTAN TENGAH'
 'KALIMANTAN TIMUR' 'KALIMANTAN UTARA' 'KEPULAUAN BANGKA BELITUNG'
 'KEPULAUAN RIAU' 'LAMPUNG' 'MALUKU' 'MALUKU UTARA' 'NUSA TENGGARA BARAT'
 'NUSA TENGGARA TIMUR' 'PAPUA' 'PAPUA BARAT' 'RIAU' 'SULAWESI BARAT'
 'SULAWESI SELATAN' 'SULAWESI TENGAH' 'SULAWESI TENGGARA' 'SULAWESI UTARA'
 'SUMATERA BARAT' 'SUMATERA SELATAN' 'SUMATERA UTARA' 'ACEH' 'BALI'
 'BANTEN' 'BENGKULU' 'DAERAH ISTIMEWA YOGYAKARTA' 'DKI JAKARTA'
 'GORONTALO' 'JAMBI' 'JAWA BARAT' 'JAWA TENGAH' 'JAWA TIMUR'
 'KALIMANTAN BARAT' 'KALIMANTAN SELATAN' 'KALIMANTAN TENGAH'
 'KALIMANTAN TIMUR' 'KALIMANTAN UTARA' 'KEPULAUAN BANGKA BELITUNG'
 'KEPULAUAN RIAU' 'LAMPUNG' 'MALUKU' 'MALUKU UTARA' 'NUSA TENGGARA BARAT'
 'NUSA TENGGARA TIMUR' 'PAPUA' 'PAPUA BARAT' 'RIAU' 'SULAWESI BARAT'
 'SULAWESI SELATAN' 'SULAWESI TENGAH' 'SULAWESI TENGGARA' 'SULAWESI UTARA'
 'SUMATERA BARAT' 'SUMATERA SELATAN' 'SUMATERA UTARA' 'ACEH' 'BALI'
 'BANTEN' 'BENGKULU' 'DAERAH ISTIMEWA YOGYAKARTA' 'DKI JAKARTA'
 'GORONTALO' 'JAMBI' 'JAWA BARAT' 'JAWA TENGAH' 'JAWA TIMUR'
 'KALIMANTAN BARAT' 'KALIMANTAN SELATAN' 'KALIMANTAN TENGAH'
 'KALIMANTAN TIMUR' 'KALIMANTAN UTARA' 'KEPULAUAN BANGKA BELITUNG'
 'KEPULAUAN RIAU' 'LAMPUNG' 'MALUKU' 'MALUKU UTARA' 'NUSA TENGGARA BARAT'
 'NUSA TENGGARA TIMUR' 'PAPUA' 'PAPUA BARAT' 'RIAU' 'SULAWESI BARAT'
 'SULAWESI SELATAN' 'SULAWESI TENGAH' 'SULAWESI TENGGARA' 'SULAWESI UTARA'
 'SUMATERA BARAT' 'SUMATERA SELATAN' 'SUMATERA UTARA']
340

In [12]:
dict1 = {'provinsi' : provinsi, 'tahun' : year, 'luas lahan' : luas }
luas = pd.DataFrame(dict1, columns=['provinsi','tahun','luas lahan'])
luas = luas.drop(luas.index[0])
luas.head()

                     provinsi  tahun   luas lahan
1                        BALI   2011   26669000.0
2                      BANTEN   2011  111622060.0
3                    BENGKULU   2011   96755672.0
4  DAERAH ISTIMEWA YOGYAKARTA   2011   10415813.0
5                 DKI JAKARTA   2011    6391800.0

# Rumah Tangga Perikanan

In [13]:
df_rtpb_raw =pd.read_excel('drive/MyDrive/Capstone Tetris/RTP Budidaya.xlsx')
df_rtpl_raw =pd.read_excel('drive/MyDrive/Capstone Tetris/RTP Laut.xlsx')
df_rtpp_raw =pd.read_excel('drive/MyDrive/Capstone Tetris/RTP PUD.xlsx')

In [14]:
df_rtpb_raw.head()

,Provinsi,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,ACEH,0,46641,47340,47649,47274,48579,48579,48680,35855,48458
1,BALI,0,14107,12527,10879,9744,10441,10441,8545,10320,10617
2,BANTEN,0,25187,24843,25169,25550,20949,20949,26646,20741,20867
3,BENGKULU,0,12942,15249,17458,20829,20622,20622,32466,28650,15371
4,DAERAH ISTIMEWA YOGYAKARTA,0,64101,67497,66976,69806,59903,59903,66763,61200,62781

In [15]:
df_rtpb_raw.shape

(34, 11)

In [16]:
jum = []
i = 1
j = 1
k = 1
while i < df_rtpb_raw.shape[1]:
    data= df_rtpb_raw.transpose().iloc[i].to_numpy()
    jum = np.concatenate((jum, data))
    i = i + 1
while j < df_rtpb_raw.shape[1]:
    data= df_rtpl_raw.transpose().iloc[j].to_numpy()
    jum = np.concatenate((jum, data))
    j = j + 1
while k < df_rtpb_raw.shape[1]:
    data= df_rtpp_raw.transpose().iloc[k].to_numpy()
    jum = np.concatenate((jum, data))
    k = k + 1
print(jum)
print(len(jum))

[0 0 0 ... 13366 43800 10555]
1020

In [17]:
tahun = []
i = 2011
j = 2011
k = 2011
while i < 2021:
    tahun.extend(repeat(i,df_rtpb_raw.shape[0]))
    i = i + 1
while j < 2021:
    tahun.extend(repeat(j,df_rtpb_raw.shape[0]))
    j = j + 1
while k < 2021:
    tahun.extend(repeat(k,df_rtpb_raw.shape[0]))
    k = k + 1
print(tahun)
print(len(tahun))

[2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020]
1020

In [18]:
prov = []
i = 1
j = 1
k = 1
while i < df_rtpb_raw.shape[1]:
    data = df_rtpb_raw.transpose().iloc[0].to_numpy()
    prov = np.concatenate((prov, data))
    i = i + 1
while j < df_rtpb_raw.shape[1]:
    data = df_rtpb_raw.transpose().iloc[0].to_numpy()
    prov = np.concatenate((prov, data))
    j = j + 1
while k < df_rtpb_raw.shape[1]:
    data = df_rtpb_raw.transpose().iloc[0].to_numpy()
    prov = np.concatenate((prov, data))
    k = k + 1
print(prov)
print(len(prov))

['ACEH' 'BALI' 'BANTEN' ... 'SUMATERA BARAT' 'SUMATERA SELATAN'
 'SUMATERA UTARA']
1020

In [19]:
jenis_rtp = []
jenis_rtp.extend(repeat('Budidaya', 340))
jenis_rtp.extend(repeat('Laut', 340))
jenis_rtp.extend(repeat('PUD', 340))
print(jenis_rtp)
print(len(jenis_rtp))

['Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Budidaya', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'Laut', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD', 'PUD']
1020

In [20]:
dict2 = {'provinsi' : prov, 'tahun' : tahun,'jenis' : jenis_rtp, 'jumlah RTP' : jum }
rtp = pd.DataFrame(dict2, columns=['provinsi','tahun','jenis', 'jumlah RTP'])
rtp = rtp.drop(rtp.index[0])
rtp.head()

                     provinsi  tahun     jenis jumlah RTP
1                        BALI   2011  Budidaya          0
2                      BANTEN   2011  Budidaya          0
3                    BENGKULU   2011  Budidaya          0
4  DAERAH ISTIMEWA YOGYAKARTA   2011  Budidaya          0
5                 DKI JAKARTA   2011  Budidaya          0

# Produk Domestik Bruto

In [77]:
pdb_raw = pd.read_excel('drive/MyDrive/Capstone Tetris/PDB.xlsx')

In [78]:
pdb_raw.head()

   Tahun  Triwulan    Nilai      Satuan
0   2011         1  36017.5  Rp. Miliar
1   2011         2  38319.5  Rp. Miliar
2   2011         3  40154.9  Rp. Miliar
3   2011         4  40053.3  Rp. Miliar
4   2012         1  39195.1  Rp. Miliar

In [79]:
pdb_raw['PDB'] = pdb_raw['Nilai'] * 1000000000
pdb_raw.head()

   Tahun  Triwulan    Nilai      Satuan           PDB
0   2011         1  36017.5  Rp. Miliar  3.601750e+13
1   2011         2  38319.5  Rp. Miliar  3.831950e+13
2   2011         3  40154.9  Rp. Miliar  4.015490e+13
3   2011         4  40053.3  Rp. Miliar  4.005330e+13
4   2012         1  39195.1  Rp. Miliar  3.919510e+13

In [80]:
pdb_group = pdb_raw.groupby('Tahun').sum()['PDB']
pdb_group.to_frame()
pdb_group = pdb_group.reset_index(level=0)
pdb_group.head()

   Tahun           PDB
0   2011  1.545452e+14
1   2012  1.642643e+14
2   2013  1.761493e+14
3   2014  1.890897e+14
4   2015  2.040168e+14

# Exploratory Data Anaylsis

## Produksi Perikanan

In [ ]:
jum_group = prod.groupby(['Jenis Usaha', 'Tahun']).sum()['Volume Produksi']
jum_group.to_frame()
jum_group = jum_group.reset_index(level= ['Jenis Usaha', 'Tahun'])
jum_group.head()

  Jenis Usaha  Tahun  Volume Produksi
0    BUDIDAYA   2011       7928962.11
1    BUDIDAYA   2012       9675490.61
2    BUDIDAYA   2013      13300905.82
3    BUDIDAYA   2014      14359129.52
4    BUDIDAYA   2015      15634093.05

In [25]:
prod_group = prod.groupby(['Jenis Usaha', 'Tahun']).sum()['Nilai Produksi']
prod_group.to_frame()
prod_group = prod_group.reset_index(level= ['Jenis Usaha', 'Tahun'])
prod_group.head()

  Jenis Usaha  Tahun  Nilai Produksi
0    BUDIDAYA   2011     66549923289
1    BUDIDAYA   2012     75922740419
2    BUDIDAYA   2013    111758806179
3    BUDIDAYA   2014    127695038337
4    BUDIDAYA   2015    121577620149

In [37]:
fig= px.line(jum_group, y = 'Volume Produksi', 
             labels = { 'Volume Produksi': 'Volume'}, 
              x = 'Tahun', color = 'Jenis Usaha',
             title = "Volume Produksi Tahunan Berdasarkan Jenis Usaha")
fig.layout.plot_bgcolor = "light grey"
fig.show()

In [26]:
fig= px.line(prod_group, y = 'Nilai Produksi', 
             labels = { 'Nilai Produksi': 'Nilai'}, 
              x = 'Tahun', color = 'Jenis Usaha',
             title = "Nilai Produksi Tahunan Berdasarkan Jenis Usaha")
fig.layout.plot_bgcolor = "light grey"
fig.show()

# Luas Lahan

In [55]:
luas_group = luas.groupby(['tahun', 'provinsi']).sum()['luas lahan']
luas_group.to_frame()
luas_group = luas_group.reset_index(level=['tahun', 'provinsi'])
luas_group.head()

   tahun                    provinsi   luas lahan
0   2011                        BALI   26669000.0
1   2011                      BANTEN  111622060.0
2   2011                    BENGKULU   96755672.0
3   2011  DAERAH ISTIMEWA YOGYAKARTA   10415813.0
4   2011                 DKI JAKARTA    6391800.0

In [28]:
fig= px.line(luas_group, y = 'luas lahan', 
             labels = { 'luas lahan': 'Luas'}, 
              x = 'tahun', color = 'provinsi',
             title = "Luas Lahan Budidaya Tahunan Berdasarkan Provinsi")
fig.layout.plot_bgcolor = "light grey"
fig.show()

In [29]:
rtp_group = rtp.groupby(['tahun', 'jenis']).sum()['jumlah RTP']
rtp_group.to_frame()
rtp_group = rtp_group.reset_index(level=['tahun', 'jenis'])
rtp_group.head()

   tahun     jenis  jumlah RTP
0   2011  Budidaya           0
1   2011      Laut      595200
2   2011       PUD      324928
3   2012  Budidaya     1670447
4   2012      Laut      627416

In [30]:
fig= px.line(rtp_group, y = 'jumlah RTP', 
             labels = { 'jumlah RTP': 'Jumlah'}, 
              x = 'tahun', color = 'jenis',
             title = "Jumlah RTP Tahunan Berdasarkan Jenis Usaha")
fig.layout.plot_bgcolor = "light grey"
fig.show()

# Korelasi Variabel

In [41]:
prod_corr = prod_group[prod_group['Jenis Usaha'] == 'BUDIDAYA']
prod_corr.drop('Jenis Usaha', axis=1, inplace=True)
prod_corr.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

   Tahun  Nilai Produksi
0   2011     66549923289
1   2012     75922740419
2   2013    111758806179
3   2014    127695038337
4   2015    121577620149

In [61]:
jum_corr = jum_group[jum_group['Jenis Usaha'] == 'BUDIDAYA']
jum_corr.drop('Jenis Usaha', axis=1, inplace=True)
jum_corr.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

   Tahun  Volume Produksi
0   2011       7928962.11
1   2012       9675490.61
2   2013      13300905.82
3   2014      14359129.52
4   2015      15634093.05

In [65]:
luas_corr = luas.groupby(['tahun']).sum()['luas lahan']
luas_corr.to_frame()
luas_corr = luas_corr.reset_index(level=['tahun'])
luas_corr = luas_corr.rename({'tahun':'Tahun', 'luas lahan':'Luas Lahan'}, axis =1)
luas_corr.head()

   Tahun    Luas Lahan
0   2011  1.046532e+10
1   2012  1.125577e+10
2   2013  1.278437e+10
3   2014  1.253748e+10
4   2015  1.321844e+10

In [69]:
rtp_corr = rtp_group[rtp_group['jenis'] == 'Budidaya']
rtp_corr.drop('jenis', axis=1, inplace=True)
rtp_corr = rtp_corr.rename({'tahun':'Tahun','jumlah RTP':'Jumlah RTP'}, axis =1)
rtp_corr.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    Tahun  Jumlah RTP
0    2011           0
3    2012     1670447
6    2013     1667428
9    2014     1649171
12   2015     1624504

In [72]:
corr = prod_corr.merge(jum_corr, on='Tahun').merge(luas_corr, on='Tahun').merge(rtp_corr, on='Tahun')
corr.head()

   Tahun  Nilai Produksi  Volume Produksi    Luas Lahan  Jumlah RTP
0   2011     66549923289       7928962.11  1.046532e+10           0
1   2012     75922740419       9675490.61  1.125577e+10     1670447
2   2013    111758806179      13300905.82  1.278437e+10     1667428
3   2014    127695038337      14359129.52  1.253748e+10     1649171
4   2015    121577620149      15634093.05  1.321844e+10     1624504

In [74]:
import plotly.figure_factory as ff
df_corr = corr[['Nilai Produksi', 'Volume Produksi', 'Luas Lahan', 'Jumlah RTP']].corr()
x = list(df_corr.columns)
y = list(df_corr.index)
z = np.array(df_corr)

fig = px.imshow(z, x=x, y=y, color_continuous_scale='Viridis', aspect="auto")
fig.update_traces(text=np.around(z, decimals=2), texttemplate="%{text}")
fig.update_xaxes(side="top")
fig.show()

In [81]:
corr1 = prod_corr.merge(pdb_group, on='Tahun')
corr1.head()

   Tahun  Nilai Produksi           PDB
0   2011     66549923289  1.545452e+14
1   2012     75922740419  1.642643e+14
2   2013    111758806179  1.761493e+14
3   2014    127695038337  1.890897e+14
4   2015    121577620149  2.040168e+14

In [82]:
fig = px.scatter(corr1, x="Nilai Produksi", y="PDB")
fig.show()

In [90]:
from scipy.stats import pearsonr

corr, _ = pearsonr(corr1["Nilai Produksi"], corr1["PDB"])
print('Pearsons correlation: %.3f' % corr)
if corr == 0:
  print('Tidak ada hubungan sama sekali')
elif corr > 0 and corr < 0.2:
  print('Hubungan sangat lemah')
elif corr >= 0.2 and corr < 0.4:
  print('Hubungan lemah')
elif corr >= 0.4 and corr < 0.6:
  print('Hubungan cukup kuat')
elif corr >= 0.6 and corr < 0.8:
  print('Hubungan kuat')
elif corr >= 0.8 and corr < 1:
  print('Hubungan sangat kuat')
elif corr == 1:
  print('Hubungan sempurna')

Pearsons correlation: 0.951
Hubungan sangat kuat

In [91]:
luas.to_csv('drive/MyDrive/Capstone Tetris/luas_lahan.csv')

In [92]:
rtp.to_csv('drive/MyDrive/Capstone Tetris/rtp.csv')